// Code generated by github.com/filecoin-project/lotus/node/config/cfgdocgen. DO NOT EDIT.

package config

type DocField struct {
	Name    string
	Type    string
	Comment string
}

var Doc = map[string][]DocField{
	"CandidateCfg": []DocField{
		{
			Name: "TcpSrvAddr",
			Type: "string",

			Comment: ``,
		},
		{
			Name: "IpfsApiURL",
			Type: "string",

			Comment: ``,
		},
	},
	"EdgeCfg": []DocField{
		{
			Name: "ListenAddress",
			Type: "string",

			Comment: `host address and port the edge node api will listen on`,
		},
		{
			Name: "Timeout",
			Type: "string",

			Comment: `used when 'ListenAddress' is unspecified. must be a valid duration recognized by golang's time.ParseDuration function`,
		},
		{
			Name: "DeviceID",
			Type: "string",

			Comment: `deivce id`,
		},
		{
			Name: "Secret",
			Type: "string",

			Comment: `used auth when connect to scheduler`,
		},
		{
			Name: "CarfilestorePath",
			Type: "string",

			Comment: `carfilestore path`,
		},
		{
			Name: "CarfilestoreType",
			Type: "string",

			Comment: `blockstore type`,
		},
		{
			Name: "BandwidthUp",
			Type: "int64",

			Comment: `upload file bandwidth, unit is B/s`,
		},
		{
			Name: "BandwidthDown",
			Type: "int64",

			Comment: `download file bandwidth, unit is B/s`,
		},
		{
			Name: "Locator",
			Type: "bool",

			Comment: `if true, get scheduler url from locator`,
		},
	},
}
